### ISSUE TITLE
Anlernmodus von Livisigeräten

### ISSUE THREAD

**Issue by metaiiica** [planbnet/livisi_unofficial#96]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

ist kein Problem

### Describe the solution you'd like

ist es möglich, neue Geräte direkt über HA anzulernen?

Würde Sinn machen wenn man Geräte hat die in Reichweite von der Zentrale ist, aber keine Wlanverbindung zur Zentrale besteht.

Letztens hatte ich im Keller (vor dem 1.3.) einen Zwischenstecker eingerichtet, ohne Cloud hätte das im Kellerbunker nie funktioniert. Hatte da LTE aber kein Wlan. Via Cloud konnte ich den Stecker einrichten

Sprich.. will wer einer ein Gerät einrichten das ausserhalb seines Heimnetzwerkes, aber in Reichweite der Zentrale ist braucht dafür eine externe Schnittstelle. Und da wäre HA perfekt dafür

Würde auch den Blödsinn VPN obsolet machen wenn man Nabu Casa nutzt.

### Describe alternatives you've considered

.

### Additional context

.

**Comment by metaiiica** [comment]
sorry, meine Idee konnte ich nicht in englisch vorstellen.. zu umfngreich

ist eh blödsinnig. Das nutzen zu 99% deutsche User. Warum wir dann englisch kommunizieren versteh ich nicht. Author deutsch, User deutsch.. warum kompliziert wenns einfach gehen könnte

**Comment by planbnet** [comment]
Ich hab schon mal erklärt, warum ich die Issues auf Englisch hielten möchte - falls diese Integration jemals wieder in Home Assistant zurückgeführt wird (was ja aufgrund der Tatsache, dass sich dort niemand mehr darum kümmert, gar nicht so unwahrscheinlich ist), macht es Sinn Fehler, Probleme und Implementierung auf Englisch zu dokumentieren. Für Feature Requests macht das vielleicht nicht so viel Sinn, allerdings ist das hier auch kein Wunschkonzert: Der Anlernmodus geht tatsächlich über das hinaus, was ich benötige (woher sollen denn auch noch groß neue Geräte kommen), daher werde ich da keine Zeit reininvestieren…

**Comment by metaiiica** [comment]
na gut, wenn nur in englisch... ok. Aber ich finde das unnötig weil es viele gibt wo Probleme haben dieser Sprache nicht mächtig sind. Das musszmt auch Du einsehen

**Comment by olli711** [comment]
> na gut, wenn nur in englisch... ok. Aber ich finde das unnötig weil es viele gibt wo Probleme haben dieser Sprache nicht mächtig sind. Das musszmt auch Du einsehen

Leider gehöre ich auch zu denen mit 55 ist das schon ne Weile her. Deswegen quäle ich mich oft mit Fehler und melde kaum welche, hinzu kommt, dass ich Windows beherrsche, aber von Linux keinen Plan habe. 

Naja, ich benutze dann halt einen Übersetzer, damit gehts auch, man wird dann nur für Blöd gehalten. 

Ich kann das aber verstehen, das man hier nicht zweisprachig mit Fehlern aggieren möchte. Dann muss man halt mit manchen Sachen leben oder nutzt ein deutschsprachiges Forum wie das von Simon. Vielleicht sollten sich die Livisi Nutzer dort zu einem eigenem Thema zusammentun. Möglichweise richtet Simon uns ja eine Abteilung ein. Das könnte man ja noch im Livisi Forum kommunizieren. 

Jedenfalls bin ich Planbet dankbar für diese geile Integration. Den Livisi Mist konnte man ja garnicht gebrauchen.


Unfortunately, I'm also one of those at 55 that's been a while. That's why I often torture myself with mistakes and hardly report any, in addition to the fact that I master Windows, but have no plan for Linux.

Well, I'll just use a translator, that's fine, you'll only be considered stupid.

But I can understand that you don't want to act bilingually with mistakes here. Then you just have to live with some things or use a German-language forum like Simon's. Maybe the Livisi users there should get together on their own topic. Maybe Simon will set up a department for us. This could still be communicated in the Livisi Forum.

In any case, I am grateful to Planbet for this great integration. You couldn't use the Livisi crap at all.
